In [3]:
import numpy 
arr = numpy.array([1,2,3,4,5]) 
print(arr)


[1 2 3 4 5]


In [8]:
import numpy as np
arr1 = np.array([1,2,3,4,5]) 
print(arr1)

[1 2 3 4 5]


In [10]:
print(np.__version__)

1.21.2


In [33]:
arr3 = np.array([[1,2,3],[4,15,6],[1,2,31],[4,5,6]]) 


In [34]:
print(arr3)

[[ 1  2  3]
 [ 4 15  6]
 [ 1  2 31]
 [ 4  5  6]]


In [21]:
print(arr1.ndim) 
print(arr3.ndim) 

1
2


In [26]:
print('index 2nd dim: ', arr3[2,2]) 

index 2nd dim:  31


In [36]:
print('Last element from 2nd dim:',arr3[-3,-2]) 

Last element from 2nd dim: 15


In [42]:
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,99,3],[4,5,6]]]) 
print(arr4)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1 99  3]
  [ 4  5  6]]]


In [39]:
print(arr4.ndim) 

3


In [41]:
print(arr4[0,0,2]) 

6


In [47]:
print(arr4[1,0,1]) 

99


In [49]:
print(arr4[0,1])

[4 5 6]


In [51]:
arr5 =np.array([1,2,3,4],ndmin=5) 

In [52]:
print(arr5)

[[[[[1 2 3 4]]]]]


In [53]:
arr6 = np.array([[1,2,3,4,5], [6,7,8,9,10]]) 


In [54]:
print(arr6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
